author: boozaa
database: false
description: "Plugin BooTreasure"
generator: Boozaa Bukkit Generator
main: org.shortrip.boozaa.plugins.bootreasure.BooTreasure
name: BooTreasure
startup: POSTWORLD
version: '0.5'
softDepend: [Vault]
commands:
  bootreasure:
    description: bootreasure
    usage: /bootreasure help
