package org.shortrip.boozaa.plugins.bootreasure.managers.configuration;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;


/*
*   Generated by Boozaa Bukkit Plugin Generator
*   Use it as you wish but please leave this header
*   I wish you good time develop your plugins
*   contact: boozaa@shortrip.org
*/
public abstract class Configuration extends YamlConfiguration {

	protected File source;
	
	
	public Configuration(JavaPlugin plugin) throws FileNotFoundException, ConfigLoadException, IOException, InvalidConfigurationException {
		this(plugin.getDataFolder() + File.separator + "config.yml");
	}
	public Configuration(String sourcepath) throws FileNotFoundException, ConfigLoadException, IOException, InvalidConfigurationException {
		this(new File(sourcepath));
	}
	public Configuration(File source) throws FileNotFoundException, ConfigLoadException, IOException, InvalidConfigurationException {
		if( !source.exists() )
			createFile();
		this.source = source;
	}
	
	public abstract void createFile() throws FileNotFoundException, ConfigLoadException, IOException, InvalidConfigurationException;
		
	@SuppressWarnings("unchecked")
	public <T> T parse(String path, T def) {
		T rval = (T) this.get(path, def);
		this.set(path, rval);
		return rval;
	}
	
	public boolean exists() {
		return this.source.exists();
	}
	
	public void init() throws ConfigLoadException, FileNotFoundException, IOException, InvalidConfigurationException {
		this.load();
		this.save();
	}
	
	public void reload() throws ConfigLoadException, FileNotFoundException, IOException, InvalidConfigurationException{
		this.save();
		this.load();
	}

	public void load() throws ConfigLoadException, FileNotFoundException, IOException, InvalidConfigurationException{
		this.load(this.source);		
	}
	
	
	public void save() {
		try {
			//boolean regen = !this.exists();
			this.save(this.source);
			//if (regen) System.out.println("[BooTreasure2] File '" + this.source + "' has been regenerated");
		} catch (Exception ex) {
			System.out.println("[BooTreasure2] Error while saving to file '" + this.source + "':");
			ex.printStackTrace();
		}
	}
	
	public <T> List<T> getListOf(String path) {
		return this.getListOf(path, new ArrayList<T>());
	}
	
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public <T> List<T> getListOf(String path, List<T> def) {
		List list = this.getList(path, null);
		if (list == null) {
			return def;
		} else {
			List<T> rval = new ArrayList<T>();
			for (Object object : this.getList(path)) {
				try {
					rval.add((T) object);
				} catch (Throwable t) {}
			}
			return rval;
		}
	}
	
	public Set<String> getKeys(String path) {
		try {
			return this.getConfigurationSection(path).getKeys(false);
		} catch (Exception ex) {
			return new HashSet<String>();
		}
	}
	

}

